### ISSUE TITLE
Build Wireframes for the Application

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/Lets-Pair-Program#9]
It could be digital via something like Balsamiq

Or, it could be just drawn either on a whiteboard or pencil / paper and a photo taken.

**Comment by DarthDARKFather** [comment]
![scan0001](https://cloud.githubusercontent.com/assets/15641570/13892301/ce0d4970-ed2c-11e5-8aae-d78c74e3ee82.JPG)
For that one I was thinking for the picture box maybe instead of what a wrote have an image slider showing pictures of the forum and examples of how to use the site. But that stuff can be added towards the end. 
![scan0002](https://cloud.githubusercontent.com/assets/15641570/13892327/fcc97a68-ed2c-11e5-9ef1-82ef17698901.JPG)
An idea of what the forum page could look like.

Let me know what you like what you don't like and suggestions.

**Comment by kenmazaika** [comment]
These look awesome to me!  Thoughts @robertsapunarich @nkholton @VictoriaBrouard

**Comment by NKHolton** [comment]
Ah I see.  For some reason after I heard yesterday's meeting recording I thought we were creating a whole new site about something else and that instead of working on the features individually we were going to pair program on each feature.  But we're creating a website for FHP students to be able to post like 'hey I'd love to PP on XYZ anyone available tomorrow at xpm?'  Am I understanding it right?

**Comment by kenmazaika** [comment]
@NKHolton - exactly!  It's a board to do pair programming.

**Comment by robertsapunarich** [comment]
Yep! That's it. @nkholton

**Comment by robertsapunarich** [comment]
Just got around to looking at these. Fantastic.
